### ISSUE TITLE
HelmService : `stream().forEach(` can be replaced with `forEach`

### ISSUE THREAD

**Issue by rohanKanojia** [eclipse-jkube/jkube#3342] opened 2024-08-28 10:57 UTC
### Component

JKube Kit

### Description
I see a warning in my IDE for this line

https://github.com/eclipse-jkube/jkube/blob/8cc048e699c982a901ec8d9236fcb1430953ece4/jkube-kit/helm/src/main/java/org/eclipse/jkube/kit/resource/helm/HelmService.java#L468

`stream()` call is unnecessary here, we should directly use `forEach` 

### Expected Behavior
`stream` call is removed from the abovementioned line

### Acceptance Criteria
- [ ] `stream().forEach(` is replaced with `forEach`
- [ ] HelmServiceTest is passing after making these changes

**Comment by manusa** [comment] 2024-08-28 10:59
duplicate of #3336

**Closed** 2024-08-28 11:02 UTC
Labels: good first issue, help wanted
