### ISSUE TITLE
OpenShiftResourceMojoTest is failing on Windows due to use of `\n`  as line separator

### ISSUE THREAD

**Issue by rohanKanojia** [eclipse-jkube/jkube#3180] opened 2024-06-19 13:51 UTC
### Component

OpenShift Maven Plugin

### Description
Related to https://github.com/eclipse/jkube/issues/1338

⚠️ A windows machine is required to reproduce and fix problems in this issue

OpenShiftResourceMojoTest is failing on windows due to expecting a Linux line ending

https://github.com/eclipse-jkube/jkube/blob/dfe163dc10aebfa470ed5cb825a1278345b11113/openshift-maven-plugin/plugin/src/test/java/org/eclipse/jkube/maven/plugin/mojo/build/OpenShiftResourceMojoTest.java#L88

This can easily be fixed by using platform independent `%n` and placing string inside `String.format()`
### Expected Behavior
OpenShiftResourceMojoTest should pass on windows

### Acceptance Criteria
- [ ] OpenShiftResourceMojoTest should pass on windows

**Comment by haseena-hassan** [comment] 2024-06-19 16:21
I would like to work on fixing this issue. Can you please assign this to me?

**Comment by Thulasithang** [comment] 2024-06-20 12:57
Hey, I would like to take this up

**Comment by Thulasithang** [comment] 2024-06-20 14:39
@rohanKanojia the builder() method for the type BuildConfiguration returns an error even though lombok.Builder is imported in the BuildConfiguration.java file. 

![image](https://github.com/eclipse-jkube/jkube/assets/115763801/8151e435-8be1-4393-b409-e36ead68c4c3)


But this is not the case for all builder() methods. Since builder() methods in some files do work without errors. 

For context, I am using vscode and I have the java extension pack so lombok works in my system.

**Comment by rohanKanojia** [comment] 2024-06-20 15:22
@Thulasithang : that's strange, I'm not VSCode user but could you please try clearing IDE cache to see if it resolves the issue?

**Comment by Thulasithang** [comment] 2024-06-21 07:37
> that's strange, I'm not VSCode user but could you please try clearing IDE cache to see if it resolves the issue?
Clearing cache didn't work unfortunately. But I was able to reproduce the correct results on IntelliJ.

**Closed** 2024-06-25 07:40 UTC
Labels: good first issue, help wanted
