### ISSUE TITLE
DependencyEnricher : Remove unnecessary `Arrays.asList` call

### ISSUE THREAD

**Issue by rohanKanojia** [eclipse-jkube/jkube#3343] opened 2024-08-28 11:02 UTC
### Component

JKube Kit

### Description
We're converting an array to a list in this line and then just iterate over the list

https://github.com/eclipse-jkube/jkube/blob/8cc048e699c982a901ec8d9236fcb1430953ece4/jkube-kit/enricher/generic/src/main/java/org/eclipse/jkube/enricher/generic/DependencyEnricher.java#L136-L141

If we just want to iterate over array items, there is no need to use `Arrays.asList` call
### Expected Behavior
Unwrap unnecessary `Arrays.asList` call

### Acceptance Criteria
- [ ] `Arrays.asList` call is unwrapped
- [ ] DependencyEnricherTest is passing after making these changes

**Comment by manusa** [comment] 2024-08-28 11:03
Duplicate of #3340

**Closed** 2024-08-28 11:07 UTC
Labels: good first issue, help wanted
