### ISSUE TITLE
Changing the default port of the embedded server does not change the K8S probes default port

### ISSUE THREAD

**Issue by manusa** [eclipse-jkube/jkube#2832] opened 2024-03-18 16:17 UTC
### Discussed in https://github.com/eclipse/jkube/discussions/2826

<div type='discussions-op-text'>

<sup>Originally posted by **waynemorphic** March 16, 2024</sup>
I was checking out the Spring Boot Quickstart provided under the Maven package and found something peculiar that I would like a little help with. The default port of the embedded server is 8080. However, I changed it to 8081 under`resources\application.yaml` with the configuration:

```
server:
  port: 8081
```

This follows that, building the Spring Boot application with `mvn spring-boot:run` serves the application on Tomcat's port 8081. 

```shell script
2024-03-16 18:55:29.067  INFO 3498 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port(s): 8081 (http)
2024-03-16 18:55:29.085  INFO 3498 --- [           main] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
2024-03-16 18:55:29.085  INFO 3498 --- [           main] org.apache.catalina.core.StandardEngine  : Starting Servlet engine: [Apache Tomcat/9.0.82]
2024-03-16 18:55:29.210  INFO 3498 --- [           main] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
2024-03-16 18:55:29.210  INFO 3498 --- [           main] w.s.c.ServletWebServerApplicationContext : Root WebApplicationContext: initialization completed in 1614 ms
2024-03-16 18:55:29.870  INFO 3498 --- [           main] o.s.b.a.e.web.EndpointLinksResolver      : Exposing 1 endpoint(s) beneath base path '/actuator'
2024-03-16 18:55:29.974  INFO 3498 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat started on port(s): 8081 (http) with context path ''
2024-03-16 18:55:29.987  INFO 3498 --- [           main] o.e.j.m.sample.spring.boot.Application   : Started Application in 3.102 seconds (JVM running for 3.656)
```

However, when running the command that creates K8S resources descriptors, i.e `mvn clean k8s:resource -Pkubernetes`, then there is a discrepancy between the ports:

```shell script
[INFO] k8s: jkube-controller: Adding a default Deployment
[INFO] k8s: jkube-service: Adding a default service 'spring-boot' with ports [8081]
[INFO] k8s: jkube-healthcheck-spring-boot: Adding readiness probe on port 8080, path='/actuator/health', scheme='HTTP', with initial delay 10 seconds
[INFO] k8s: jkube-healthcheck-spring-boot: Adding liveness probe on port 8080, path='/actuator/health', scheme='HTTP', with initial delay 180 seconds
[INFO] k8s: jkube-service-discovery: Using first mentioned service port '8081' 
```

What I have tried so far with the invaluable help of @rohanKanojia was adding the following property in my POM file:

```shell script
<properties>
    <jkube.version>${project.version}</jkube.version>
    <jkube.generator.spring-boot.webPort>8081</jkube.generator.spring-boot.webPort>
  </properties>
```
However, the above port discrepancy persists. Guidance on this will be helpful. Thank you
</div>

**Comment by arsenalzp** [comment] 2024-03-19 09:31
Hello,
Is it possible to work for this issue?

**Comment by rohanKanojia** [comment] 2024-03-19 09:54
@arsenalzp : Please see my comment https://github.com/eclipse/jkube/pull/2800#issuecomment-1997598182 for some code pointers related to this issue. If you need more help, please don't hesitate to ping me.

**Comment by arsenalzp** [comment] 2024-03-27 21:57
The issue is that the call ``SpringBootConfiguration.from(getContext().getProject());`` returns the different configuration.
As you may see at the screenshot Spring Boot port was changed from 8080 to 8081, I used ``<jkube.generator.spring-boot.webPort>8081</jkube.generator.spring-boot.webPort>`` property to override the default port for the embedded server.

![изображение](https://github.com/eclipse/jkube/assets/46520164/0432ed41-9e48-4a2e-9b28-78adebfe4629)


However, ``SprongBootConfiguration`` call returns wrong value which doesn't reflect the changed default port

**Comment by rohanKanojia** [comment] 2024-04-02 18:00
@arsenalzp : Hello, Sorry I was PTO last week. 

> I used <jkube.generator.spring-boot.webPort>8081</jkube.generator.spring-boot.webPort> property to override the default port for the embedded server.

You're configuring the generator (responsible for creating container images) but running `k8s:resource` goal (responsible for generating Kubernetes manifests. As far as I remember @waynemorphic was trying to configure Spring Application's configuration in `src/main/resources/appliation.yml`:
```yaml
server:
  port: 8081
```

Do you have `application.yml` file present in `src/main/resources` ?

The expected behavior is to automatically detect Spring Boot Configuration and use that port.

**Comment by arsenalzp** [comment] 2024-04-05 09:06
> @arsenalzp : Hello, Sorry I was PTO last week.
> 
> > I used <jkube.generator.spring-boot.webPort>8081</jkube.generator.spring-boot.webPort> property to override the default port for the embedded server.
> 
> You're configuring the generator (responsible for creating container images) but running `k8s:resource` goal (responsible for generating Kubernetes manifests. As far as I remember @waynemorphic was trying to configure Spring Application's configuration in `src/main/resources/appliation.yml`:
> 
> ```yaml
> server:
>   port: 8081
> ```
> 
> Do you have `application.yml` file present in `src/main/resources` ?
> 
> The expected behavior is to automatically detect Spring Boot Configuration and use that port.

Hello,
Yest, I know the difference between enrichers and generators, I just wanted to reproduce all the step described in the initial message of this issue.

**Comment by rohanKanojia** [comment] 2024-04-05 09:10
generators  -> classes responsible for creating container images as per different frameworks by inspecting project dependencies

enrichers -> classes responsible for creating Kubernetes manifests  by checking project depednencies/ setup.

**Comment by arsenalzp** [comment] 2024-04-05 09:14
Last week and begging of the current one I was on vacations dues to the Easter, so I will keep working on this issueб with your permission.

**Comment by rohanKanojia** [comment] 2024-04-05 09:16
@arsenalzp :  Please take your time and don't worry about the delay, there are no strict deadlines here.

**Comment by arsenalzp** [comment] 2024-04-05 18:38
> @arsenalzp : Please take your time and don't worry about the delay, there are no strict deadlines here.

Thank you!
I've just arrived at home and checked the second question asked by you regarding `resources` path - answer is YES, I put the files in the right directory, as described in Spring Boot docs:

```/jkube/quickstarts/maven/spring-boot/src/main/resources```

Spring Boot instance boots up with the right port defined in application.yaml.

**Comment by arsenalzp** [comment] 2024-04-06 18:14
Here is the screenshot of old version. As you may see both `yamlResources` and `propertiesResources` objects are null:

![изображение](https://github.com/eclipse/jkube/assets/46520164/3d2974bf-0f78-4734-a43b-9b742f072732)

Checking paths:

![изображение](https://github.com/eclipse/jkube/assets/46520164/4eeba35a-ee8a-436b-91d5-3e5ec896fb6d)

The full list of paths defined in `compilerClassLoader.ucp.path` field:

> file:/home/arsenal/eclipse-workspace/jkube/quickstarts/maven/spring-boot/target/classes/
 file:/home/arsenal/eclipse-workspace/jkube/quickstarts/maven/spring-boot/target/classes/
 file:/home/arsenal/.m2/repository/org/springframework/boot/spring-boot-starter-web/2.7.17/spring-boot-starter-web-2.7.17.jar
 file:/home/arsenal/.m2/repository/org/springframework/boot/spring-boot-starter/2.7.17/spring-boot-starter-2.7.17.jar
 file:/home/arsenal/.m2/repository/org/springframework/boot/spring-boot/2.7.17/spring-boot-2.7.17.jar
 file:/home/arsenal/.m2/repository/org/springframework/boot/spring-boot-autoconfigure/2.7.17/spring-boot-autoconfigure-2.7.17.jar
 file:/home/arsenal/.m2/repository/org/springframework/boot/spring-boot-starter-logging/2.7.17/spring-boot-starter-logging-2.7.17.jar
 file:/home/arsenal/.m2/repository/ch/qos/logback/logback-classic/1.2.12/logback-classic-1.2.12.jar
 file:/home/arsenal/.m2/repository/ch/qos/logback/logback-core/1.2.12/logback-core-1.2.12.jar
 file:/home/arsenal/.m2/repository/org/slf4j/slf4j-api/1.7.36/slf4j-api-1.7.36.jar
 file:/home/arsenal/.m2/repository/org/apache/logging/log4j/log4j-to-slf4j/2.17.2/log4j-to-slf4j-2.17.2.jar
 file:/home/arsenal/.m2/repository/org/apache/logging/log4j/log4j-api/2.17.2/log4j-api-2.17.2.jar
 file:/home/arsenal/.m2/repository/org/slf4j/jul-to-slf4j/1.7.36/jul-to-slf4j-1.7.36.jar
 file:/home/arsenal/.m2/repository/jakarta/annotation/jakarta.annotation-api/1.3.5/jakarta.annotation-api-1.3.5.jar
 file:/home/arsenal/.m2/repository/org/springframework/spring-core/5.3.30/spring-core-5.3.30.jar
 file:/home/arsenal/.m2/repository/org/springframework/spring-jcl/5.3.30/spring-jcl-5.3.30.jar
 file:/home/arsenal/.m2/repository/org/yaml/snakeyaml/1.30/snakeyaml-1.30.jar
 file:/home/arsenal/.m2/repository/org/springframework/boot/spring-boot-starter-json/2.7.17/spring-boot-starter-json-2.7.17.jar
 file:/home/arsenal/.m2/repository/com/fasterxml/jackson/core/jackson-databind/2.13.5/jackson-databind-2.13.5.jar
 file:/home/arsenal/.m2/repository/com/fasterxml/jackson/core/jackson-annotations/2.13.5/jackson-annotations-2.13.5.jar
 file:/home/arsenal/.m2/repository/com/fasterxml/jackson/core/jackson-core/2.13.5/jackson-core-2.13.5.jar
 file:/home/arsenal/.m2/repository/com/fasterxml/jackson/datatype/jackson-datatype-jdk8/2.13.5/jackson-datatype-jdk8-2.13.5.jar
 file:/home/arsenal/.m2/repository/com/fasterxml/jackson/datatype/jackson-datatype-jsr310/2.13.5/jackson-datatype-jsr310-2.13.5.jar
 file:/home/arsenal/.m2/repository/com/fasterxml/jackson/module/jackson-module-parameter-names/2.13.5/jackson-module-parameter-names-2.13.5.jar
 file:/home/arsenal/.m2/repository/org/springframework/boot/spring-boot-starter-tomcat/2.7.17/spring-boot-starter-tomcat-2.7.17.jar
 file:/home/arsenal/.m2/repository/org/apache/tomcat/embed/tomcat-embed-core/9.0.82/tomcat-embed-core-9.0.82.jar
 file:/home/arsenal/.m2/repository/org/apache/tomcat/embed/tomcat-embed-el/9.0.82/tomcat-embed-el-9.0.82.jar
 file:/home/arsenal/.m2/repository/org/apache/tomcat/embed/tomcat-embed-websocket/9.0.82/tomcat-embed-websocket-9.0.82.jar
 file:/home/arsenal/.m2/repository/org/springframework/spring-web/5.3.30/spring-web-5.3.30.jar
 file:/home/arsenal/.m2/repository/org/springframework/spring-beans/5.3.30/spring-beans-5.3.30.jar
 file:/home/arsenal/.m2/repository/org/springframework/spring-webmvc/5.3.30/spring-webmvc-5.3.30.jar
 file:/home/arsenal/.m2/repository/org/springframework/spring-aop/5.3.30/spring-aop-5.3.30.jar
 file:/home/arsenal/.m2/repository/org/springframework/spring-context/5.3.30/spring-context-5.3.30.jar
 file:/home/arsenal/.m2/repository/org/springframework/spring-expression/5.3.30/spring-expression-5.3.30.jar
 file:/home/arsenal/.m2/repository/org/springframework/boot/spring-boot-starter-actuator/2.7.17/spring-boot-starter-actuator-2.7.17.jar
 file:/home/arsenal/.m2/repository/org/springframework/boot/spring-boot-actuator-autoconfigure/2.7.17/spring-boot-actuator-autoconfigure-2.7.17.jar
 file:/home/arsenal/.m2/repository/org/springframework/boot/spring-boot-actuator/2.7.17/spring-boot-actuator-2.7.17.jar
 file:/home/arsenal/.m2/repository/io/micrometer/micrometer-core/1.9.16/micrometer-core-1.9.16.jar
 file:/home/arsenal/.m2/repository/org/hdrhistogram/HdrHistogram/2.1.12/HdrHistogram-2.1.12.jar
 file:/home/arsenal/.m2/repository/org/jolokia/jolokia-core/1.7.2/jolokia-core-1.7.2.jar
 file:/home/arsenal/.m2/repository/com/googlecode/json-simple/json-simple/1.1.1/json-simple-1.1.1.jar

**Comment by rohanKanojia** [comment] 2024-04-08 07:42
Are you able to see `application.yml` file in `file:/home/username/eclipse-workspace/jkube/quickstarts/maven/spring-boot/target/classes/` ? 

I see this behavior. When I don't run `mvn package` before running `mvn k8s:resource` `application.yml` file is not copied to `target/classes` . The plugin expects the spring `application.yml` file to be present in this path, if it doesn't find this file it reverts to opinionted defaults.

When I do `mvn package k8s:resource` I'm able to see correct port being set in generated manfiests.

**Comment by arsenalzp** [comment] 2024-04-08 08:06
> Are you able to see `application.yml` file in `file:/home/username/eclipse-workspace/jkube/quickstarts/maven/spring-boot/target/classes/` ?
> 
> I see this behavior. When I don't run `mvn package` before running `mvn k8s:resource` `application.yml` file is not copied to `target/classes` . The plugin expects the spring `application.yml` file to be present in this path, if it doesn't find this file it reverts to opinionted defaults.
> 
> When I do `mvn package k8s:resource` I'm able to see correct port being set in generated manfiests.

Hello,
Yes, I see `application.yml` in `target/classes` which is copied by `mvn package`, however I guess this behavior is wrong, file `application.yml` must be processed by `mvn k8s:resource` from `src/main/resources/` path without any advance preparation.

Otherwise, if command `mvn package` is required before `mvn k8s:resource` then no bug is observed here, just need to update doc and close the issue.

**Comment by manusa** [comment] 2024-04-09 07:35
> Otherwise, if command `mvn package` is required before `mvn k8s:resource` then no bug is observed here, just need to update doc and close the issue.
> 
> P.S. I guess, my patch is bringing straightforward and independent way of generating K8S resources. Imagine user has medium or even big java project, user just need a simple k8s deployment resource for it, so to get it user has to run `mvn package` command before run `mvn k8s:resource` one, it leads to run over all preceding phases: validate, compile, test!

The problem is that some projects perform filtering and transformation on src resources, that's why JKube considers the final classes, resources and artifacts as processed by the compile (and others) lifecycle goals.

It's also strange (in my opinion) that you want to generate the deployment file from the sources instead of the compiled files. `[...]user just need a simple k8s deployment resource for it[...]` I can't really think of a realistic use case where this would happen.


Regarding the issue itself, I'm not sure if this issue is also related to #2665

**Comment by arsenalzp** [comment] 2024-04-09 07:52
Thank you for your feedback, it is very appreciated.
Let's produce a decision here, if no bug being is observed then we can close this particular issue, otherwise I can put changes in my PR to reflect all your remarks and wishes which are necessary.

**Comment by manusa** [comment] 2024-04-09 10:44
As I see it:

Having a fallback to read resources from additional places might be an improvement to the user experience.
However, this brings in a set of additional problems:
- Resources are not always located at `src/main/resources`
- Users who post-process their resources might end up consuming wrong resources if they forget to process their resources prior to running the `k8s:resource` goal (i.e. the opposite of the problem you are reporting as part of this issue)

From my perspective, unless there's some specific scenario where this is providing a real benefit and we can overcome the aforementioned issues, then we should do it.

Otherwise, the only thing we can try to consider is providing extra-information about how the exposed port was inferred to help users that run into your same problem.

**Comment by arsenalzp** [comment] 2024-04-10 21:19
> As I see it:
> 
> Having a fallback to read resources from additional places might be an improvement to the user experience. However, this brings in a set of additional problems:
> 
>     * Resources are not always located at `src/main/resources`
> 
>     * Users who post-process their resources might end up consuming wrong resources if they forget to process their resources prior to running the `k8s:resource` goal (i.e. the opposite of the problem you are reporting as part of this issue)
> 
> 
> From my perspective, unless there's some specific scenario where this is providing a real benefit and we can overcome the aforementioned issues, then we should do it.
> 
> Otherwise, the only thing we can try to consider is providing extra-information about how the exposed port was inferred to help users that run into your same problem.

We can allow user to set up resource directory to consume resources from user's directory (within project context dir, of course).
However, `src/main/resources` path is pretty common among many Java project.


Anyway, working on this issue was very good experience for me to deep dive into this great project!

Decision is up to you, guys

**Comment by manusa** [comment] 2024-04-11 05:05
> However, src/main/resources path is pretty common among many Java project.

It's the default for Maven and usually for Gradle. However, you can define multiple resource directories, rename this directory (don't use its default location), add filtering capabilities, and so on. For example, in Maven, the Apache Maven Resources Plugin is responsible for all this (https://maven.apache.org/plugins/maven-resources-plugin/).

IMO the only thing we can do is try to add a helpful or debug message stating where/how was the application port inferred from, probably at the Generator level (will very likely require changes for each supported framework).

**Comment by arsenalzp** [comment] 2024-04-11 07:43
> > However, src/main/resources path is pretty common among many Java project.
> 
> It's the default for Maven and usually for Gradle. However, you can define multiple resource directories, rename this directory (don't use its default location), add filtering capabilities, and so on. For example, in Maven, the Apache Maven Resources Plugin is responsible for all this (https://maven.apache.org/plugins/maven-resources-plugin/).
> 
> IMO the only thing we can do is try to add a helpful or debug message stating where/how was the application port inferred from, probably at the Generator level (will very likely require changes for each supported framework).

Agree with you.
I can fix my code to reflect your remarks. So, I keep the current PR code, just gonna add debug message.
Does it sound good?

**Comment by arsenalzp** [comment] 2024-04-22 17:39
@manusa hello,
I've just added INFO message for demo purposes. I have feelings the last commit has a smell, however there are not so many opportunities and places in the code where properties file (`application.yml` or `application.properties`) could be set/get.

**Comment by rohanKanojia** [comment] 2024-04-22 18:04
@arsenalzp : Hello, I'm assuming you're running this in `quickstarts/maven/spring-boot`. I tried running `mvn k8s:resource -Djkube.version=1.17-SNAPSHOT` but couldn't reproduce the issue. My Git remote is in the following format:

```
$ git remote -v
origin  git@github.com:rohanKanojia/jkube.git (fetch)
origin  git@github.com:rohanKanojia/jkube.git (push)
```

This warning is coming from GitEnricher when JKube tries to add git annotations to generated Kubernetes manifests:
https://github.com/eclipse-jkube/jkube/blob/a6215610db7080f2f9394565240086f0da80275e/jkube-kit/enricher/generic/src/main/java/org/eclipse/jkube/enricher/generic/GitEnricher.java#L59
Somehow in your case `gitRemoteUrl` is coming as `null`

**Comment by rohanKanojia** [comment] 2024-04-22 18:30
@arsenalzp : Is it possible for you to set a breakpoint in GitEnricher and run `mvnDebug k8s:resource` , it would start a remove JVM debug sesssion; You can connect via your IDE and go step by step to see what's actually happening in your case.

**Comment by arsenalzp** [comment] 2024-04-22 18:46
> @arsenalzp : Is it possible for you to set a breakpoint in GitEnricher and run `mvnDebug k8s:resource` , it would start a remove JVM debug sesssion; You can connect via your IDE and go step by step to see what's actually happening in your case.

I'm doing exact the same.

**Comment by arsenalzp** [comment] 2024-04-25 11:36
Hello colleagues,
I would appreciate any feedback/remarks on my PR. Any kind of feedback is very appreciated!

**Comment by rohanKanojia** [comment] 2024-04-25 11:51
@arsenalzp : Thanks for taking time to look into this! I now understand that you're getting the error due to your remote name `micronaut4` .
In GitEnricher, it only expects remote name to be `origin`. Custom remote names need to be configured via `jkube.remoteName` property.

https://github.com/eclipse-jkube/jkube/blob/78a7989f6debcab7cc62bc179ddd3170242dd00c/jkube-kit/enricher/generic/src/main/java/org/eclipse/jkube/enricher/generic/GitEnricher.java#L108-L110

**Comment by rohanKanojia** [comment] 2024-04-25 12:05
@arsenalzp : I think it's okay to create a draft PR so that the team can also check.

**Comment by arsenalzp** [comment] 2024-04-25 12:15
> @arsenalzp : I think it's okay to create a draft PR so that the team can also check.

Could this PR https://github.com/eclipse-jkube/jkube/pull/2880 be converted to draft one?

What was done:
1) take into account `src/main/resources` path where `spring-boot`  application properties files are put in.
2) print info message which path was taken: either `target/classes`/ or `src/main/resources/`

**Comment by rohanKanojia** [comment] 2024-04-25 13:47
@arsenalzp : I'll try to check your PR later today.

**Closed** 2024-10-21 13:28 UTC
Labels: bug
