### ISSUE TITLE
imagePullSecrets I wonder when this property will be supported?

### ISSUE THREAD

**Issue by qichen111** [eclipse-jkube/jkube#3092] opened 2024-05-23 09:21 UTC
### Component

Kubernetes Maven Plugin

### Is your enhancement related to a problem? Please describe

 I wonder when this property will be supported?

### Describe the solution you'd like

 I wonder when this property will be supported?

### Describe alternatives you've considered

 I wonder when this property will be supported?

### Additional context

 I wonder when this property will be supported?

**Comment by rohanKanojia** [comment] 2024-05-27 10:07
Duplicate of #2467

**Comment by rohanKanojia** [comment] 2024-05-27 10:09
@qichen111 : I think this was requested last year also. I've linked an issue with this. Do you think it's covering your use case? Or is it something different?

I had added some code pointers in #2467 so that it could be picked up by other community members. Would it be possible for you to contribute this ?

**Closed** 2024-06-07 08:40 UTC
Labels: enhancement
